# Generated by Django 3.2.9 on 2021-11-15 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 15, 10, 19, 37, 337535, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
